name: Scala CI (Farkle)

on:
  push:
    branches: [ main, feature-ci-pipeline ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Project
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '26'
        cache: 'sbt'

    - name: Setup sbt launcher
      uses: sbt/setup-sbt@v1

    - name: Run Tests and Coverage
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: sbt clean coverage test coverageReport coveralls
      
    - name: Run Mutation Testing (Stryker4s)
      run: sbt stryker